blog/urls.py
from django.conf.urls import url

from .views import BlogIndex, BlogView

urlpatterns = [
    url(r'^$', BlogIndex.as_view(), name="index"),
    url(r'^blog/(?P<slug>\S+)$', BlogView.as_view(), name="page"),
]

theproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^markdown/', include("django_markdown.urls")),
    url(r'^', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^', include('userprofile.urls', namespace='profile', app_name='profile')),
]

userprofile/urls.py
from django.conf.urls import url

from .views import ContactView, ProfileView

urlpatterns = [
    url(r'^about-me/$', ProfileView.as_view(), name="index"),
    url(r'^contact/$', ContactView.as_view(), name="contact"),
]

blog/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.text import slugify

from django_markdown.models import MarkdownField


# blog models
class Tag(models.Model):
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.slug


class EntryQuerySet(models.QuerySet):
    def published(self):
        return self.filter(publish=True)


class Entry(models.Model):
    title = models.CharField(max_length=200)
    body = MarkdownField()
    slug = models.SlugField(max_length=200, unique=True)
    publish = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(User)

    objects = EntryQuerySet.as_manager()

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Entry, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:page', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = "Blog Entry"
        verbose_name_plural = "Blog Entries"
        ordering = ["-created"]

userprofile/models.py
from django.contrib.auth.models import User
from django.db import models


class UserProfile(models.Model):
    user = models.OneToOneField(User)

    def __unicode__(self):
        return self.user.username

userprofile/forms.py
from django import forms
from django.core.mail import EmailMessage

EMAIL_RECIPIENT_LIST = 'rustydude09@gmail.com'


class ContactForm(forms.Form):
    phone_invalid = "Phone number format must be :'+999999999'. Up to 15 digits allowed."

    name = forms.CharField(max_length=255)
    email = forms.EmailField()
    phone = forms.RegexField(regex=r'^\+?1?\d{9,15}$', error_messages={'invalid': phone_invalid})
    message = forms.CharField(widget=forms.Textarea)

    def send_email(self, form):
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        phone = form.cleaned_data['phone']
        message = form.cleaned_data['message']

        info = '{} <{}|{}>'.format(name, email, phone)
        email = EmailMessage(info, message, to=[EMAIL_RECIPIENT_LIST])
        email.send()

blog/views.py
from django.views.generic import DetailView, ListView

from .models import Entry


class BlogIndex(ListView):
    queryset = Entry.objects.published()
    template_name = "home.html"
    paginate_by = 3


class BlogView(DetailView):
    model = Entry
    template_name = "blog_page.html"

userprofile/views.py
from django.core.urlresolvers import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import ListView
from django.views.generic.edit import FormView

from .forms import ContactForm
from .models import UserProfile


class ProfileView(ListView):
    model = UserProfile
    template_name = "about.html"


class ContactView(SuccessMessageMixin, FormView):
    template_name = "contact.html"
    form_class = ContactForm
    success_url = reverse_lazy("profile:contact")
    success_message = "This message was sent successfully, I will try to get back to you as soon as possible!"

    def form_valid(self, form):
        form.send_email(form)
        return super(ContactView, self).form_valid(form)

templates/about.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
<title>About Me: Russel Adrian Lopez : Django Developer in Jacksonville, FL</title>
{% endblock %}

{% block page_header %}   
<header class="intro-header" style="background-image: url({% static 'img/about-bg.jpg' %})">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="page-heading">
                    <h1>About Me</h1>
                    <hr class="small">
                    <span class="subheading">The things that I could do.</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block content %}
    <h2>Skills</h2>
        <ul>
            <li>Mainly focuses on the field of Web Development: Specializes in building websites with Django Web Framework</li>
            <li>Basic Fundamentals of Web Design: HTML, CSS and Javascript.</li>
            <li>Familiar with Agile/Scrum Methodology and also very familiar with using git.
            <li>Minor Experience with DevOps: nginx, apache</li>
            <li>Minor skills with Quality Assurance: Manual Testing, Automated Testing, Test Driven Technology</li>
            <li>Minor skills with Multimedia Tools: Adobe Photoshop, Adobe Audition, Adobe Premium, Seny Vegas Pro</li>
            </ul>
    <h2>Work Experience</h2>
        <ul>
            <li>Intern at Philippine Global Outsourcing. Trained as a Andriod mobile developer developed a prototype book finder application.</li>
            <li>Began working with Django upon my graduation and worked as a remote developer under Ingenuity Global Consulting, Inc.</li>
            <li>Work with a swedish company called The Inspiration Company. Working with a reward shop system application.</li>
        </ul>
    <h2>Personal and Education info</h2>
        <ul>
            <li>Born and raised in Tagum City, Davao Del Norte, Philippines.</li>
            <li>Graduated from Ateneo De Davao University with a degree in Computer Science</li>
            <li>Recently migrated into the US and moved in Jacksonville, Florida.</li>
            <li>Plays some basketball and video games to satisfy competitiveness.</li>
        </ul>

    <h2>Resume</h2>
    <table>
        <thead>
            <tr>
                <td><h3 style="text-align:center"> Graphic Resume</h3></td>
                <td><h3 style="text-align:center"> SoftCopy Resume</h3></td>
            </tr>
            <tr>
                <td style="width:50%;height: 100%">
                     <a href="https://drive.google.com/file/d/0B1PHFuHY5NdfZ1dhMWJrd2I3TkU/view?usp=sharing">
                        <img src="{% static 'img/Resume1.jpg' %}" alt="Resume #1" style="max-width:100%; max-height: 100%;">
                    </a>
                </td>

                <td style="padding-left:5px;width:50%;height: 100%">
                    <a href="https://docs.google.com/document/d/1W5I3bs_iEzuRxqhGXCEwRFYdkFEP22_mqe5EmLknhZ4/edit?usp=sharing">
                        <img src="{% static 'img/Resume2.jpg' %}" alt="Resume #2" style="max-width: 100%; max-height: 100%;">
                    </a>
                </td>
            </tr>
        </thead>
    </table>
{% endblock %}

templates/base.html
{% load staticfiles %}
{% load django_markdown %}
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="">
      <meta name="author" content="">

      {% block title %}{% endblock %}

      <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />
      <link rel="icon" type="image/ico" href="{% static 'img/favicon.ico' %}"  />


      <!-- Bootstrap Core CSS -->
      <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

      <!-- Custom CSS -->
      <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">


      <!-- Custom Fonts -->
      <link href="{% static 'css/font-awesome.css' %}" type="text/css">
      <link href="{% static 'css/font-lora.css' %}" rel='stylesheet' type='text/css'>
      <link href="{% static 'css/font-open-sans.css' %}" rel='stylesheet' type='text/css'>

  </head>

  <body>

      <!-- Navigation -->
      <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
          <div class="container-fluid">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header page-scroll">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="{% url 'profile:index' %}">TheRusselProject</a>
              </div>

              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav navbar-right">
                      <li>
                          <a href="{% url 'blog:index' %}">Home</a>
                      </li>
                      <li>
                          <a href="{% url 'profile:index' %}">About Me</a>
                      </li>
                      <li>
                          <a href="{% url 'profile:contact' %}">Contact Me</a>
                      </li>
                  </ul>
              </div>
              <!-- /.navbar-collapse -->
          </div>
          <!-- /.container -->
      </nav>

      <!-- Page Header -->
      <!-- Set your background image for this header on the line below. --> 
      {% block page_header %} {% endblock %}

      <!-- Main Content -->
      <div class="container">
          <div class="row">
              <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                  {% block content %} {% endblock %}
              </div>
          </div>
      </div>

      <hr>

      <!-- Footer -->
      <footer>
          <div class="container">
              <div class="row">
                  <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                      <ul class="list-inline text-center">
                          <li>
                              <a href="skype:russeladrian.lopez?add">
                                  <span class="fa-stack fa-lg">
                                      <i class="fa fa-circle fa-stack-2x"></i>
                                      <i class="fa fa-skype fa-stack-1x fa-inverse"></i>
                                  </span>
                              </a>
                          </li>
                          <li>
                              <a href="mailto:rustydude09@gmail.com">
                                  <span class="fa-stack fa-lg">
                                      <i class="fa fa-circle fa-stack-2x"></i>
                                      <i class="fa fa-google fa-stack-1x fa-inverse"></i>
                                  </span>
                              </a>
                          </li>
                          <li>
                              <a href="https://github.com/rustydude">
                                  <span class="fa-stack fa-lg">
                                      <i class="fa fa-circle fa-stack-2x"></i>
                                      <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                  </span>
                              </a>
                          </li>
                      </ul>
                      <p class="copyright text-muted">Copyright &copy; 2015 Russel Adrian Lopez  // Built with <a href="https://www.djangoproject.com/">Django<a></p>
                  </div>
              </div>
          </div>
      </footer>


      {% block js %}
      <!-- jQuery -->
      <script src="{% static 'js/jquery.js' %}"></script>

      <!-- Bootstrap Core JavaScript -->
      <script src="{% static 'js/bootstrap.min.js' %}"></script>

      {% endblock %}
  </body>

</html>

templates/blog_page.html
{% extends "base.html" %}
{% load staticfiles %}
{% load django_markdown %}

{% block title %}
<title>Blog:{{ object.slug }}: Russel Adrian Lopez : Django Developer in Jacksonville, FL</title>
{% endblock %}

{% block page_header %}
<header class="intro-header" style="background-image: url({% static 'img/blog-page-bg.jpg' %})">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-heading">
                    <h1>{{ object.title }}</h1>
                    <h2 class="subheading">{{ object.body|markdown|truncatewords:"8"|linebreaks }}</h2>
                    <span class="meta">Posted by <a href="{% url 'profile:index' %}">{{ object.author }}</a> on {{ object.created }}</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

    <!-- Post Content -->
<article>
    {% block content %}
    <h2 class="section-heading"><a href="{% url "blog:page" slug=object.slug %}">{{object.title}}</a></h2>

    <p>{{ object.body|markdown }}</p>
    {% endblock %}
</article>

templates/contact.html
{% extends "base.html" %}
{% load staticfiles %}
{% load django_markdown %}
{% load widget_tweaks %}
{% load widget_tweaks %}

{% block title %}
<title>Contact: Russel Adrian Lopez : Django Developer in Jacksonville, FL</title>
{% endblock %}

{% block page_header %}
<header class="intro-header" style="background-image: url({% static 'img/contact-bg.jpg' %})">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="page-heading">
                    <h1>Contact Me</h1>
                    <hr class="small">
                    <span class="subheading">Have any more questions?</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}
{% if messages %}
    {% for message in messages %}
        <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
    {% endfor %}
    {% else %}
        <p>Want to get in touch with me? Fill out the form below to send me a message.</p>
{% endif %}

    <form method="post" name="sentMessage" id="contactForm"> {% csrf_token %}
        {{ form.non_field_errors }}
         <div class="row control-group">
            <div class="fieldWrapper form-group col-xs-12 floating-label-form-group controls">
                {{ form.name.errors }}
                <label for="{{ form.name.id_for_label }}">Name</label>
                {{ form.name|add_class:"form-control"|attr:"placeholder:Name"|attr:"required data-validation-required-message:Please enter your name." }}
                <p class="help-block text-danger"></p>
            </div>
        </div>
        <div class="row control-group">
            <div class="fieldWrapper form-group col-xs-12 floating-label-form-group controls">
                {{ form.email.errors }}
                <label for="{{ form.email.id_for_label }}">Email Address</label>
                {{ form.email|add_class:"form-control"|attr:"placeholder:Email Address"|attr:"required data-validation-required-message:Please enter your name."  }}
                <p class="help-block text-danger"></p>
            </div>
        </div>
        <div class="row control-group">
            <div class="fieldWrapper form-group col-xs-12 floating-label-form-group controls">
                {{ form.phone.errors }}
                <label for="{{ form.phone.id_for_label }}">Phone Number</label>
                {{ form.phone|add_class:"form-control"|attr:"placeholder:Phone Number"|attr:"required data-validation-required-message:Please enter your phone number."  }}
                <p class="help-block text-danger"></p>
            </div>
        </div>
        <div class="row control-group">
            <div class="fieldWrapper form-group col-xs-12 floating-label-form-group controls">
                {{ form.message.errors }}
                <label for="{{ form.message.id_for_label }}">Message</label>
                {{ form.message|attr:"row:5"|add_class:"form-control"|attr:"placeholder:Message"|attr:"required data-validation-required-message:Please enter your message."  }}
                <p class="help-block text-danger"></p>
            </div>
        </div>
        <br>
        <div id="success"></div>
        <div class="row">
            <div align="center" class="form-group col-xs-12">
                <button type="submit" class="btn btn-default">Send</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load staticfiles %}
{% load django_markdown %}

{% block title %}
<title>Blog: Russel Adrian Lopez : Django Developer in Jacksonville, FL</title>
{% endblock %}
    

{% block page_header %}
<header class="intro-header" style="background-image: url({% static 'img/home-bg.jpg' %})">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>Russel Adrian Lopez</h1>
                    <hr class="small">
                    <span class="subheading">I am a Django Web Developer.</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}
{% for object in object_list %}
<div class="post-preview">
        <h2 class="post-title">
            <a href="{% url "blog:page" slug=object.slug %}">{{object.title}}
        </h2>
        
        <h3 class="post-subtitle">
            {{ object.body|markdown|truncatewords:"20"|linebreaks }}</a>
        </h3>
    </a>
    <p class="post-meta">Posted by <a href="#">{{ object.author }}</a> on {{ object.created }}</p>
</div>
{% endfor %}
<!-- Pager -->
{% if is_paginated %}
<ul class="pager">
    <li {% if not page_obj.has_previous %} class="hidden" {% endif %}>
        <a {% if page_obj.has_previous %} href="?page={{ page_obj.previous_page_number }}" {% endif %}>&larr; Newer Posts</a>
    </li>
    <li {% if not page_obj.has_next %} class="hidden" {% endif %}>
        <a {% if page_obj.has_next %} href="?page={{ page_obj.next_page_number }}" {% endif %}>Older Posts &rarr;</a>
    </li>
</ul>
{% endif %}
{% endblock %}